# Generated by Django 5.2.4 on 2025-07-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_course_coures_image_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='section',
            field=models.CharField(max_length=30),
        ),
    ]
