# Generated by Django 5.2.4 on 2025-07-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_classroom_name_alter_classroom_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='major',
            field=models.CharField(default='mathe', max_length=100),
        ),
    ]
