# Generated by Django 5.2.4 on 2025-07-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacher_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='major',
            field=models.CharField(max_length=100),
        ),
    ]
