# Generated by Django 5.2.4 on 2025-07-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teacher_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='year',
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade',
            field=models.CharField(choices=[('First Grade', 'First Grade'), ('Second Grade', 'Second Grade'), ('Third Grade', 'Third Grade'), ('Fourth Grade', 'Fourth Grade'), ('Fifth Grade', 'Fifth Grade'), ('Sixth Grade', 'Sixth Grade')], default='First Grade', max_length=50),
        ),
    ]
