# Generated by Django 5.2.4 on 2025-07-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_remove_classroom_year_classroom_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='name',
        ),
    ]
