# Generated by Django 5.2.4 on 2025-07-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_classroom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomcourse',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
