# Generated by Django 5.2.4 on 2025-07-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_attendance_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
